language: node_js
node_js:
  - 'stable'
os: [linux]
dist: trusty
sudo: required
cache:
  yarn: true
after_success:
  - yarn build && netlify deploy --site NETLIFY_SITE_ID --auth NETLIFY_AUTH_TOKEN --prod --dir=public
