language: node_js
node_js:
  - '10'
os:
  - linux
dist: trusty
sudo: required
cache:
  yarn: true
before_deploy:
  - yarn add netlify-cli
  - yarn build
deploy:
  provider: script
  script: netlify deploy -s \${NETLIFY_SITE_ID} -t \${NETLIFY_ACCESS_TOKEN} ./build
  skip_cleanup: true
  on:
    all_branches: true
  provider: script
  script: netlify deploy -s \${NETLIFY_SITE_ID} -t \${NETLIFY_ACCESS_TOKEN} ./build --prod --dir=public
  skip_cleanup: true
  on:
    branch: master
env:
  matrix:
    - secure: ZVlRAyvRDWOwaAoGiZGY4eEw6tOKvRn80oZGSrgVIfo+PcBMtsdJwkJSJWvVQtur9WTE0OadkprSr+cznZ6SgejoKw4SiNRxA3dpawejdtVEWUntTZ32medvDOIkEle/HIm8CTOZ+eih/jpvF/fEs3X1Yr5Y+nqmoqsGRCHBYRxiqpZ4yR7oforUShE/s2bBnFabXGi3YjR16HvmMk214kRd7K3Mk/FEKyw1JFIGksQuOqT4Td9EryLHAwmraffuNWSZfo+7DWspj3STveJrAcV3e9mLZckKngr14DdJtcWCG9m92x7DLU6CcRCD5j+pfgxStZbWaLLdSJhyhnTZQ3BYlSQY/TjkCGoWxze6R+BBL/lyrEqq6Xz2d5VwG/MxbrVsEbietCdULFGDacNMNwTCbivAIJYXgqdq6BTiba4XpnAUBTDX6qmWVbnLjE+MlGKcFO9s59xx2OtIweLFzA0DOvbORYUnK2x5XQA8hbN10rhU5EUcVbdZv4FfDlh3yf3CENdZGcBgWP57tHzFXrmyQXYuLubSccHliBSsvH70gjYoKyToaGbrz0jpTaOzrMCL2ySaoEzi4cC0ouYw02B/QaHEx+AZw0hp7wDfo1UOTkgGNoRxQey6B0Nvmhe5ed9/QPY+QgGK7tw62FgDUm+vxSdoyMJ1aGzeVuQuBHY=
    - secure: h0o2QwgUBXp1dvS7jOPkqOQhGXq3rclga0LHvxyjmJ6luYK/9+nik2vUvsnmDsf+OTHOQcVcBYw058iU2aO0h1SgeMyTNqV7tIABjTYPcTeFC7W7BgIEhhHV1xTKQlfQSjaYrq+OJvXyRsea5QL74Nlg0h/y7DUY2wvIBI6bTL2sGhVMBo94H5W7dXfkHZzYOp4xrmjHxKkry7BAOMmnr5gv5TSFFPYFFVno1HJXXBFBm7LLagzI5p1AgVz4o7tW6CHaX1uaTAK7tFK6vj67KDFyoE8ijqyXlITTA1Uh7Owf1XpO+FRrpoBgw6+QpyH1stNHLYivC39VaNYhq0gzip3wIZCNkHeb/18oVfMRd4gph0eZJY0JMJQQDGfPUlLdqRR/1XMXyviTXuN9vqBC9F47IDUDtLdAyFqkSG5zRby3aMFOLtU212EGI3jLBtVIRe5RmyaT5k4NbzG/hNhc17vnjvFS+DXz1DtzTGNQoI7JZ0uQuOebFw299YubByo1yyu7TmiaDMM/q80rAS2UGUtIzrpeg96Tp2DkUvhMtWYi4eHVwpdG0O/O1OmaLcmH2j5Laep0gQ2a1wNKYxl735wsg0WsHBKr1yoKrGt5U4EkybKwgTVhBYBNwPTx2svIjbhEx0AONe0Dm5ULbKf2IO5RIUR8KGHq7ey+Os0Zx6ow=
    - secure: ILQFwBF4z2/yezT1rMGawSVshuCBPMJ+1y2lPljmcNQIHTFxrRNB96AvqElf7JQSaVvPnJslWkj9ZFnPHRgg1e6iffMqRIke1RLQT5OUOmIw6R5bPjuiRVryR1+UsrnR1d4KwWuCwtxoUGpKUXiC0d99PmxMPLWtLmCSxT51PY3ZfQtMqNdfsYTLM6Cml60kT83q3BBC3zobCDiOUZxf0K9Etf4PLUawEweMIRofauUErgyNYmLRZxQNBCTHqiuxI56xzf8Lrx0KuZtWFrvyWoWIv52KND/Z12HG953chHin2drbx4nXyy4PJLx/WQntVWiIEGDKLIzN/QeFfdBzgxGPHxxVzFUEkxRPskdbxHikrB6vcfuwIjA4bTSAm7xFPow2hZIUgpvKVbrjz7haMnHLflXmbDPRpuVsZdvWubo7PfK2foqw5Dp5efl6Nmfo63BhDAMi1gfdjOw5/AnVZzhxo/ExTHL0ERG2qATmZ4qEcQDW2HI4/74B4P84XFnZ8k/iVdp1b03Gi8cgZwaXGTzuUP7jWLMoGQT+zBaek7U7cp06YWGxpKBIBK3e35Oz3zQQ8i7uh7FuIkH6ijrzFpPF49i8jzmpke2Gd+p2JayfQoHVEXojHhnZw2A1dNh2n+O/PEGxKATHWxxfnjodbDGgPuaI6I/QqxAUmL14URs=
