name: Publish

on:
  push:
    branches:
      - master
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.FONT_AWESOME_TOKEN }}" > ~/.npmrc
          npm install
          npm run build --if-present
          netlify deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --prod --dir=public
        env:
          CD: true
          FONT_AWESOME_TOKEN: ${{ secrets.FONT_AWESOME_TOKEN }}
